### ISSUE TITLE
errors not decorated with status

### ISSUE THREAD

**Issue by aivong3** [fastly/expressly#38]
**Version**

2.0.1

**What happened**

Please describe what you did, what you expected to happen, and what happened instead.

When creating error middleware, the `err` parameter is of type `Error` which does not have the `status` property. The expressly [docs](https://expressly.edgecompute.app/docs/routing#custom-404) mention errors would be decorated with status.

The typescript error is:
```
Property 'status' does not exist on type 'Error'.
```

**Comment by doramatadora** [comment]
Thank you so much for reporting this. A fix has shipped in `v2.2.0`
