### ISSUE TITLE
Cannot extend the `request` object without losing type inference

### ISSUE THREAD

**Issue by ddaza** [fastly/expressly#40]
**Version**

```"@fastly/expressly": "^2.0.1"```

**What happened**

We are having trouble trying to Type middlewares that would stub the `request` Object.

A common `express.js` pattern is to enhance the `req` and add new functionality to store data or add helper methods using middlewares.  ie. `express-session`, `body-parser` to name a few. 

We tried to do that, but we cannot find a way to Type the new methods/functionality because of the way the Request object is typed.

I opened a PR to address some of this. And would love some feedback.

**Comment by ddaza** [comment]
PR in question:  https://github.com/fastly/expressly/pull/41

**Comment by doramatadora** [comment]
Thank you so much for raising this issue, and taking the time to contribute the fix.  This has now shipped in `v2.1.0` 🙌🏼
